opt_in_rules: # some rules are only opt-in
- first_where
- last_where
- contains_over_first_not_nil
- empty_string
- empty_count
- sorted_first_last
- collection_alignment
- identical_operands
- implicit_return
- lower_acl_than_parent
- modifier_order
- operator_usage_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

analyzer_rules:
  - unused_private_declaration
  - unused_import
